org: arash
app: berigame
# For full config options, check the docs:
#    docs.serverless.com

service: berigame-api
frameworkVersion: '4.17.0'

provider:
  name: aws
  profile: appricot2
  runtime: nodejs20.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-2
  environment:
    JWT_SECRET: "${self:custom.secrets.JWT_SECRET}"
    GOOGLE_CLIENT_ID: "${self:custom.secrets.GOOGLE_CLIENT_ID}"
    DB: ${self:service}-${opt:stage, self:provider.stage}
    APIG_ENDPOINT:
      Fn::Join:
        - ''
        - - Ref: WebsocketsApi
          - .execute-api.
          - Ref: AWS::Region
          - .amazonaws.com/
          - ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"

functions:
  - ${file(./functions.yml)}

resources:
  - ${file(./database.yml)}

custom:
  secrets: ${file(secrets.json)}
        
plugins:
  - serverless-offline
